### ISSUE TITLE
[typo]: `use` -> `user`

### ISSUE THREAD

**Issue by ILikeIneine** [Life4gal/prometheus#1]
[Typo here](https://github.com/Life4gal/prometheus/blob/bf642f2b1c25d6ce33d7694bd72ad7a9f86cbca9/src/error/debug_win.hpp#L55C47-L55C51)

**Comment by Life4gal** [comment]
https://github.com/Life4gal/prometheus/blob/37afe64277df8580876bbf67524212ca4fed3342/src/error/debug.impl.ixx#L57
